version: "3.9"

services:
  api:
    build: .
    container_name: webgis_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./service_account:/app/service_account:ro
      - ./app/data:/app/app/data:ro
    restart: unless-stopped
